apiVersion: v1
data:
  enable_scripting: "false"
  exit_timeout: "0"
  idle_timeout: "14400"
  initial_timeout: "30"
  omp_threads: "8"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: carta-backend-config
