apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sanele
  namespace: carta
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: carta.your-domain.com
      http:
        paths:
          - path: /user/sakhile(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: sanele
                port:
                  number: 80
